Repository xvzc/SpoofDPI, pull requests merged in 2024-09, with the labels that each got.

#230 fix: packet processing for http request
  packet/http.go
  proxy/handler/conn.go
  proxy/handler/http.go
  proxy/handler/https.go
  proxy/handler/io.go
  proxy/proxy.go
Labels: fix

#238 refactor: correction in debugging messages
  proxy/handler/http.go
  proxy/handler/https.go
  proxy/https.go
  proxy/server.go
Labels: chore

#234 chore: add quiet option to arguments
  README.md
  _docs/README_ja.md
  _docs/README_ko.md
  _docs/README_ru.md
  _docs/README_zh-cn.md
  cmd/spoofdpi/main.go
  util/args.go
  util/config.go
Labels: chore

#240 feat: add the ability to disable ipv6 resolution for dns
  dns/dns.go
  util/args.go
  util/config.go
Labels: feature
