Repository xvzc/SpoofDPI, pull requests merged in 2024-08, with the labels that each got.

#177 fix: IPv6 support
  cmd/spoof-dpi/main.go
  dns/resolver/doh.go
  util/os.go
Labels: fix

#182 chore: refactor logging
  cmd/spoof-dpi/main.go
  dns/dns.go
  go.mod
  go.sum
  proxy/http.go
  proxy/https.go
  proxy/proxy.go
  proxy/server.go
  util/context.go
  util/log/log.go
Labels: enhancement

#183 fix: proxy settings are not reverted after panic
  cmd/spoof-dpi/main.go
Labels: fix

#191 Refactor proxy setting
  cmd/spoof-dpi/main.go
  util/os.go
Labels: enhancement

#203 Update permission error message
  util/os.go
Labels: enhancement

#204 Update installation guide
  _docs/INSTALL.md
Labels: documentation, enhancement

#206 docs: fix typos in README.md
  README.md
Labels: documentation

#198 fix: get ctx logger on new request
  proxy/proxy.go
  util/log/log.go
Labels: fix

#208 Use Google Distroless for compact images
  Dockerfile
Labels: enhancement

#231 chore: change types of flags that can't be negative to uint*
  util/args.go
  util/config.go
Labels: enhancement
